<?php

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(
        [
            'key'                   => 'group_60926594e73e3',
            'title'                 => 'CRS Page Middle block 2',
            'fields'                => [
                [
                    'key'               => 'field_609265d6a95a8',
                    'label'             => 'Contents',
                    'name'              => 'contents',
                    'type'              => 'repeater',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'collapsed'         => '',
                    'min'               => 0,
                    'max'               => 0,
                    'layout'            => 'block',
                    'button_label'      => '',
                    'sub_fields'        => [
                        [
                            'key'               => 'field_609266c80fca1',
                            'label'             => 'Header',
                            'name'              => 'header',
                            'type'              => 'text',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => [
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ],
                            'default_value'     => '',
                            'placeholder'       => '',
                            'prepend'           => '',
                            'append'            => '',
                            'maxlength'         => '',
                        ],
                        [
                            'key'               => 'field_609266da0fca2',
                            'label'             => 'Content',
                            'name'              => 'content',
                            'type'              => 'wysiwyg',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => [
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ],
                            'default_value'     => '',
                            'tabs'              => 'all',
                            'toolbar'           => 'full',
                            'media_upload'      => 1,
                            'delay'             => 0,
                        ],
                        [
                            'key'               => 'field_609266ee0fca3',
                            'label'             => 'Picture',
                            'name'              => 'picture',
                            'type'              => 'image',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => [
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ],
                            'return_format'     => 'array',
                            'preview_size'      => 'medium',
                            'library'           => 'all',
                            'min_width'         => '',
                            'min_height'        => '',
                            'min_size'          => '',
                            'max_width'         => '',
                            'max_height'        => '',
                            'max_size'          => '',
                            'mime_types'        => '',
                        ],
                    ],
                ],
                [
                    'key'               => 'field_609265ffa95a9',
                    'label'             => 'Link Text',
                    'name'              => 'link_text',
                    'type'              => 'link',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'return_format'     => 'array',
                ],
            ],
            'location'              => [
                [
                    [
                        'param'    => 'block',
                        'operator' => '==',
                        'value'    => 'acf/crs-page-middle-block2',
                    ],
                ],
            ],
            'menu_order'            => 0,
            'position'              => 'normal',
            'style'                 => 'default',
            'label_placement'       => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen'        => '',
            'active'                => true,
            'description'           => '',
        ]
    );

    acf_add_local_field_group(
        [
            'key'                   => 'group_6088fb42639f4',
            'title'                 => 'CRS Post button block',
            'fields'                => [
                [
                    'key'               => 'field_6088fb5fba2dd',
                    'label'             => 'Button',
                    'name'              => 'button',
                    'type'              => 'link',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'return_format'     => 'array',
                ],
            ],
            'location'              => [
                [
                    [
                        'param'    => 'block',
                        'operator' => '==',
                        'value'    => 'acf/crs-page-button',
                    ],
                ],
            ],
            'menu_order'            => 0,
            'position'              => 'normal',
            'style'                 => 'default',
            'label_placement'       => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen'        => '',
            'active'                => true,
            'description'           => '',
        ]
    );

    acf_add_local_field_group(
        [
            'key'                   => 'group_6092bf07557e2',
            'title'                 => 'Page with posts',
            'fields'                => [
                [
                    'key'               => 'field_6092bf1695cfe',
                    'label'             => 'Page',
                    'name'              => 'page',
                    'type'              => 'post_object',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'post_type'         => '',
                    'taxonomy'          => '',
                    'allow_null'        => 0,
                    'multiple'          => 0,
                    'return_format'     => 'object',
                    'ui'                => 1,
                ],
            ],
            'location'              => [
                [
                    [
                        'param'    => 'widget',
                        'operator' => '==',
                        'value'    => 'pageselectorwidget',
                    ],
                ],
            ],
            'menu_order'            => 0,
            'position'              => 'normal',
            'style'                 => 'default',
            'label_placement'       => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen'        => '',
            'active'                => true,
            'description'           => '',
        ]
    );

    acf_add_local_field_group(
        [
            'key'                   => 'group_609f8a2d7a22e',
            'title'                 => 'Special headline',
            'fields'                => [
                [
                    'key'               => 'field_609f8a3adfa18',
                    'label'             => 'Special headline',
                    'name'              => 'headline',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'default_value'     => 'Headline example',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ],
            ],
            'location'              => [
                [
                    [
                        'param'    => 'block',
                        'operator' => '==',
                        'value'    => 'acf/crs-special-headline',
                    ],
                ],
            ],
            'menu_order'            => 0,
            'position'              => 'normal',
            'style'                 => 'default',
            'label_placement'       => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen'        => '',
            'active'                => true,
            'description'           => '',
        ]
    );

    acf_add_local_field_group(
        [
            'key'                   => 'group_60781ba587214',
            'title'                 => 'CRS Page Top block 1',
            'fields'                => [
                [
                    'key'               => 'field_60781c41cc6c2',
                    'label'             => 'Page Menu',
                    'name'              => 'page_menu',
                    'type'              => 'repeater',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'collapsed'         => '',
                    'min'               => 0,
                    'max'               => 0,
                    'layout'            => 'table',
                    'button_label'      => '',
                    'sub_fields'        => [
                        [
                            'key'               => 'field_6078210b30181',
                            'label'             => 'Text item',
                            'name'              => 'text',
                            'type'              => 'text',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => [
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ],
                            'default_value'     => '',
                            'placeholder'       => '',
                            'prepend'           => '',
                            'append'            => '',
                            'maxlength'         => '',
                        ],
                    ],
                ],
                [
                    'key'               => 'field_60811d053c00b',
                    'label'             => 'Header',
                    'name'              => 'header',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ],
                [
                    'key'               => 'field_60782b0a8785d',
                    'label'             => 'Link text',
                    'name'              => 'link_text',
                    'type'              => 'link',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'return_format'     => 'array',
                ],
                [
                    'key'               => 'field_6081416496e2c',
                    'label'             => 'Picture',
                    'name'              => 'picture',
                    'type'              => 'image',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'return_format'     => 'array',
                    'preview_size'      => 'medium',
                    'library'           => 'all',
                    'min_width'         => '',
                    'min_height'        => '',
                    'min_size'          => '',
                    'max_width'         => '',
                    'max_height'        => '',
                    'max_size'          => '',
                    'mime_types'        => '',
                ],
            ],
            'location'              => [
                [
                    [
                        'param'    => 'block',
                        'operator' => '==',
                        'value'    => 'acf/crs-page-top-block1',
                    ],
                ],
            ],
            'menu_order'            => 1,
            'position'              => 'normal',
            'style'                 => 'default',
            'label_placement'       => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen'        => '',
            'active'                => true,
            'description'           => '',
        ]
    );

    acf_add_local_field_group(
        [
            'key'                   => 'group_607ff040d4fdb',
            'title'                 => 'CRS Page Top block 2',
            'fields'                => [
                [
                    'key'               => 'field_607ff4ffb1d5d',
                    'label'             => 'Header',
                    'name'              => 'header',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ],
                [
                    'key'               => 'field_607ff509b1d5e',
                    'label'             => 'Paragraph',
                    'name'              => 'paragraph',
                    'type'              => 'repeater',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'collapsed'         => '',
                    'min'               => 0,
                    'max'               => 0,
                    'layout'            => 'table',
                    'button_label'      => '',
                    'sub_fields'        => [
                        [
                            'key'               => 'field_607ff51fb1d5f',
                            'label'             => 'Paragraph',
                            'name'              => 'paragraph',
                            'type'              => 'textarea',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => [
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ],
                            'default_value'     => '',
                            'placeholder'       => '',
                            'maxlength'         => '',
                            'rows'              => '',
                            'new_lines'         => '',
                        ],
                    ],
                ],
                [
                    'key'               => 'field_607ff56db1d60',
                    'label'             => 'Link Text',
                    'name'              => 'link_text',
                    'type'              => 'link',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'return_format'     => 'array',
                ],
                [
                    'key'               => 'field_6081586dda017',
                    'label'             => 'Picture',
                    'name'              => 'picture',
                    'type'              => 'image',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'return_format'     => 'array',
                    'preview_size'      => 'medium',
                    'library'           => 'all',
                    'min_width'         => '',
                    'min_height'        => '',
                    'min_size'          => '',
                    'max_width'         => '',
                    'max_height'        => '',
                    'max_size'          => '',
                    'mime_types'        => '',
                ],
            ],
            'location'              => [
                [
                    [
                        'param'    => 'block',
                        'operator' => '==',
                        'value'    => 'acf/crs-page-top-block2',
                    ],
                ],
            ],
            'menu_order'            => 2,
            'position'              => 'normal',
            'style'                 => 'default',
            'label_placement'       => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen'        => '',
            'active'                => true,
            'description'           => '',
        ]
    );

    acf_add_local_field_group(
        [
            'key'                   => 'group_607d42b5edfc4',
            'title'                 => 'CRS Page Top block 3',
            'fields'                => [
                [
                    'key'               => 'field_609f961abb34d',
                    'label'             => 'Header content',
                    'name'              => 'header_content',
                    'type'              => 'wysiwyg',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'default_value'     => '',
                    'tabs'              => 'all',
                    'toolbar'           => 'full',
                    'media_upload'      => 1,
                    'delay'             => 0,
                ],
                [
                    'key'               => 'field_609f9c1a881b4',
                    'label'             => 'Address part (header with line after)',
                    'name'              => 'address_part_header_with_line',
                    'type'              => 'wysiwyg',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'default_value'     => '',
                    'tabs'              => 'all',
                    'toolbar'           => 'full',
                    'media_upload'      => 1,
                    'delay'             => 0,
                ],
                [
                    'key'               => 'field_609f963fbb34e',
                    'label'             => 'Address part content',
                    'name'              => 'address_part_content',
                    'type'              => 'wysiwyg',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'default_value'     => '',
                    'tabs'              => 'all',
                    'toolbar'           => 'full',
                    'media_upload'      => 1,
                    'delay'             => 0,
                ],
                [
                    'key'               => 'field_607d50f1f566b',
                    'label'             => 'Google maps	button',
                    'name'              => 'button',
                    'type'              => 'link',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'return_format'     => 'array',
                ],
                [
                    'key'               => 'field_60a4c76dbf7e6',
                    'label'             => 'Google map url',
                    'name'              => 'google_map_url',
                    'type'              => 'url',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'default_value'     => '',
                    'placeholder'       => '',
                ],
            ],
            'location'              => [
                [
                    [
                        'param'    => 'block',
                        'operator' => '==',
                        'value'    => 'acf/crs-page-top-block3',
                    ],
                ],
            ],
            'menu_order'            => 3,
            'position'              => 'normal',
            'style'                 => 'default',
            'label_placement'       => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen'        => '',
            'active'                => true,
            'description'           => '',
        ]
    );

    acf_add_local_field_group(
        [
            'key'                   => 'group_60811a5c9362b',
            'title'                 => 'CRs Page Top block 4',
            'fields'                => [
                [
                    'key'               => 'field_60811a738693f',
                    'label'             => 'Header',
                    'name'              => 'header',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ],
                [
                    'key'               => 'field_60811ae74cc84',
                    'label'             => 'Paragraph',
                    'name'              => 'paragraph',
                    'type'              => 'wysiwyg',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'default_value'     => '',
                    'placeholder'       => '',
                    'maxlength'         => '',
                    'rows'              => '',
                    'new_lines'         => '',
                ],
                [
                    'key'               => 'field_6081617d25d86',
                    'label'             => 'Picture',
                    'name'              => 'picture',
                    'type'              => 'image',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'return_format'     => 'array',
                    'preview_size'      => 'medium',
                    'library'           => 'all',
                    'min_width'         => '',
                    'min_height'        => '',
                    'min_size'          => '',
                    'max_width'         => '',
                    'max_height'        => '',
                    'max_size'          => '',
                    'mime_types'        => '',
                ],
            ],
            'location'              => [
                [
                    [
                        'param'    => 'block',
                        'operator' => '==',
                        'value'    => 'acf/crs-page-top-block4',
                    ],
                ],
            ],
            'menu_order'            => 4,
            'position'              => 'normal',
            'style'                 => 'default',
            'label_placement'       => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen'        => '',
            'active'                => true,
            'description'           => '',
        ]
    );

    acf_add_local_field_group(
        [
            'key'                   => 'group_60784e4782c5a',
            'title'                 => 'CRS Page Middle block 1',
            'fields'                => [
                [
                    'key'               => 'field_60784eacac931',
                    'label'             => 'Paragraph',
                    'name'              => 'paragraph',
                    'type'              => 'repeater',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'collapsed'         => '',
                    'min'               => 0,
                    'max'               => 0,
                    'layout'            => 'table',
                    'button_label'      => '',
                    'sub_fields'        => [
                        [
                            'key'               => 'field_60792b63f0999',
                            'label'             => 'Paragraph',
                            'name'              => 'paragraph',
                            'type'              => 'wysiwyg',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => [
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ],
                            'default_value'     => '',
                            'placeholder'       => '',
                            'maxlength'         => '',
                            'rows'              => '',
                            'new_lines'         => '',
                        ],
                    ],
                ],
                [
                    'key'               => 'field_60784ed6ac932',
                    'label'             => 'Button',
                    'name'              => 'button',
                    'type'              => 'link',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'return_format'     => 'array',
                ],
                [
                    'key'               => 'field_60784f0bac933',
                    'label'             => 'Picture 01',
                    'name'              => 'picture_01',
                    'type'              => 'image',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'return_format'     => 'array',
                    'preview_size'      => 'medium',
                    'library'           => 'all',
                    'min_width'         => '',
                    'min_height'        => '',
                    'min_size'          => '',
                    'max_width'         => '',
                    'max_height'        => '',
                    'max_size'          => '',
                    'mime_types'        => '',
                ],
                [
                    'key'               => 'field_607931d7c6fcf',
                    'label'             => 'Picture 02',
                    'name'              => 'picture_02',
                    'type'              => 'image',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'return_format'     => 'array',
                    'preview_size'      => 'medium',
                    'library'           => 'all',
                    'min_width'         => '',
                    'min_height'        => '',
                    'min_size'          => '',
                    'max_width'         => '',
                    'max_height'        => '',
                    'max_size'          => '',
                    'mime_types'        => '',
                ],
                [
                    'key'               => 'field_607931eac6fd0',
                    'label'             => 'Picture 03',
                    'name'              => 'picture_03',
                    'type'              => 'image',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'return_format'     => 'array',
                    'preview_size'      => 'medium',
                    'library'           => 'all',
                    'min_width'         => '',
                    'min_height'        => '',
                    'min_size'          => '',
                    'max_width'         => '',
                    'max_height'        => '',
                    'max_size'          => '',
                    'mime_types'        => '',
                ],
            ],
            'location'              => [
                [
                    [
                        'param'    => 'block',
                        'operator' => '==',
                        'value'    => 'acf/crs-page-middle-block1',
                    ],
                ],
            ],
            'menu_order'            => 5,
            'position'              => 'normal',
            'style'                 => 'default',
            'label_placement'       => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen'        => '',
            'active'                => true,
            'description'           => '',
        ]
    );

    acf_add_local_field_group(
        [
            'key'                   => 'group_607d53dac0c36',
            'title'                 => 'CRS Page Middle block 3',
            'fields'                => [
                [
                    'key'               => 'field_607d5fdaee349',
                    'label'             => 'Header',
                    'name'              => 'header',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ],
                [
                    'key'               => 'field_607d61780c374',
                    'label'             => 'Contact',
                    'name'              => 'contact',
                    'type'              => 'wysiwyg',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'default_value'     => '',
                    'tabs'              => 'all',
                    'toolbar'           => 'full',
                    'media_upload'      => 1,
                    'delay'             => 0,
                ],
                [
                    'key'               => 'field_607d7265f68cc',
                    'label'             => 'Person',
                    'name'              => 'person',
                    'type'              => 'repeater',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'collapsed'         => '',
                    'min'               => 0,
                    'max'               => 0,
                    'layout'            => 'block',
                    'button_label'      => '',
                    'sub_fields'        => [
                        [
                            'key'               => 'field_607d7281f68cd',
                            'label'             => 'Photo',
                            'name'              => 'photo',
                            'type'              => 'image',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => [
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ],
                            'return_format'     => 'array',
                            'preview_size'      => 'medium',
                            'library'           => 'all',
                            'min_width'         => '',
                            'min_height'        => '',
                            'min_size'          => '',
                            'max_width'         => '',
                            'max_height'        => '',
                            'max_size'          => '',
                            'mime_types'        => '',
                        ],
                        [
                            'key'               => 'field_60938776a7b36',
                            'label'             => 'Paragraph',
                            'name'              => 'paragraph',
                            'type'              => 'wysiwyg',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => [
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ],
                            'default_value'     => '',
                            'tabs'              => 'all',
                            'toolbar'           => 'full',
                            'media_upload'      => 1,
                            'delay'             => 0,
                        ],
                    ],
                ],
            ],
            'location'              => [
                [
                    [
                        'param'    => 'block',
                        'operator' => '==',
                        'value'    => 'acf/crs-page-middle-block3',
                    ],
                ],
            ],
            'menu_order'            => 7,
            'position'              => 'normal',
            'style'                 => 'default',
            'label_placement'       => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen'        => '',
            'active'                => true,
            'description'           => '',
        ]
    );

    acf_add_local_field_group(
        [
            'key'                   => 'group_60794c0194fac',
            'title'                 => 'CRS Page Bottom block 1',
            'fields'                => [
                [
                    'key'               => 'field_60794d2f38b66',
                    'label'             => 'Picture',
                    'name'              => 'picture',
                    'type'              => 'image',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'return_format'     => 'array',
                    'preview_size'      => 'medium',
                    'library'           => 'all',
                    'min_width'         => '',
                    'min_height'        => '',
                    'min_size'          => '',
                    'max_width'         => '',
                    'max_height'        => '',
                    'max_size'          => '',
                    'mime_types'        => '',
                ],
                [
                    'key'               => 'field_60794d4438b67',
                    'label'             => 'Header',
                    'name'              => 'header',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ],
                [
                    'key'               => 'field_60794d5d38b68',
                    'label'             => 'Paragraph',
                    'name'              => 'paragraph',
                    'type'              => 'wysiwyg',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'default_value'     => '',
                    'placeholder'       => '',
                    'maxlength'         => '',
                    'rows'              => '',
                    'new_lines'         => '',
                ],
                [
                    'key'               => 'field_60794d6d38b69',
                    'label'             => 'Button',
                    'name'              => 'button',
                    'type'              => 'link',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'return_format'     => 'array',
                ],
            ],
            'location'              => [
                [
                    [
                        'param'    => 'block',
                        'operator' => '==',
                        'value'    => 'acf/crs-page-bottom-block1',
                    ],
                ],
            ],
            'menu_order'            => 8,
            'position'              => 'normal',
            'style'                 => 'default',
            'label_placement'       => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen'        => '',
            'active'                => true,
            'description'           => '',
        ]
    );

    acf_add_local_field_group(
        [
            'key'                   => 'group_60810ee584798',
            'title'                 => 'CRS Page Bottom block 2',
            'fields'                => [
                [
                    'key'               => 'field_60810f6e89d4e',
                    'label'             => 'Header',
                    'name'              => 'header',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ],
                [
                    'key'               => 'field_60810fe762fc2',
                    'label'             => 'Buttons',
                    'name'              => 'buttons',
                    'type'              => 'repeater',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'collapsed'         => '',
                    'min'               => 0,
                    'max'               => 0,
                    'layout'            => 'table',
                    'button_label'      => '',
                    'sub_fields'        => [
                        [
                            'key'               => 'field_60810ff662fc3',
                            'label'             => 'Button',
                            'name'              => 'button',
                            'type'              => 'link',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => [
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ],
                            'return_format'     => 'array',
                        ],
                    ],
                ],
            ],
            'location'              => [
                [
                    [
                        'param'    => 'block',
                        'operator' => '==',
                        'value'    => 'acf/crs-page-bottom-block2',
                    ],
                ],
            ],
            'menu_order'            => 9,
            'position'              => 'normal',
            'style'                 => 'default',
            'label_placement'       => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen'        => '',
            'active'                => true,
            'description'           => '',
        ]
    );

    acf_add_local_field_group(
        [
            'key'                   => 'group_607d664c5c440',
            'title'                 => 'CRS Page Bottom posts',
            'fields'                => [
                [
                    'key'               => 'field_609f9113123e7',
                    'label'             => 'Left side',
                    'name'              => 'left_side',
                    'type'              => 'wysiwyg',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'default_value'     => '',
                    'tabs'              => 'all',
                    'toolbar'           => 'full',
                    'media_upload'      => 1,
                    'delay'             => 0,
                ],
                [
                    'key'               => 'field_607d680612f95',
                    'label'             => 'Posts',
                    'name'              => 'posts',
                    'type'              => 'repeater',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'collapsed'         => '',
                    'min'               => 0,
                    'max'               => 0,
                    'layout'            => 'table',
                    'button_label'      => '',
                    'sub_fields'        => [
                        [
                            'key'               => 'field_607d681a12f96',
                            'label'             => 'Post',
                            'name'              => 'post',
                            'type'              => 'post_object',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => [
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ],
                            'post_type'         => [
                                0 => 'post',
                            ],
                            'taxonomy'          => '',
                            'allow_null'        => 0,
                            'multiple'          => 0,
                            'return_format'     => 'object',
                            'ui'                => 1,
                        ],
                    ],
                ],
            ],
            'location'              => [
                [
                    [
                        'param'    => 'block',
                        'operator' => '==',
                        'value'    => 'acf/crs-page-bottom-posts',
                    ],
                ],
            ],
            'menu_order'            => 10,
            'position'              => 'normal',
            'style'                 => 'default',
            'label_placement'       => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen'        => '',
            'active'                => true,
            'description'           => '',
        ]
    );
}
