version: "3.7"

x-volumes-list:
  - &app-sources ${HOST_SRC_PATH}:${CONTAINER_SRC_PATH}

services:
  node:
    build:
      context: ./node
      dockerfile: ./Dockerfile
      target: development
      args:
        NODE_VERSION: 15.14
    working_dir: ${CONTAINER_SRC_PATH}/web/app/plugins/
    user: node
    volumes:
      - *app-sources
    environment:
      HOST_USER_ID: ${HOST_USER_ID}
      TIMEZONE: ${TIMEZONE:-Europe/Minsk}
      CHANGE_UID: ${CHANGE_UID:-1}
