#!/usr/bin/env bash

set -euo pipefail

# https://xdebug.org/docs/all_settings
if [[ $(/usr/local/bin/php -r "echo (int) phpversion('xdebug');") == 3 ]]; then

  cat <<EOF >/usr/local/etc/php/conf.d/zz-xdebug.ini
xdebug.cli_color = 1
xdebug.trigger_value = 1
xdebug.client_host = ${XDEBUG_CLIENT_HOST:-localhost}
xdebug.client_port = ${XDEBUG_CLIENT_PORT:-9003}
xdebug.mode = ${XDEBUG_MODE:-off}
xdebug.start_with_request = ${XDEBUG_START_WITH_REQUEST:-no}
xdebug.log = ${XDEBUG_LOG_FILE:-""}
xdebug.log_level = ${XDEBUG_LOG_LEVEL:-7}
EOF

  exit
fi

# https://2.xdebug.org/docs/all_settings
if [[ $(/usr/local/bin/php -r "echo (int) phpversion('xdebug');") == 2 ]]; then

  cat <<EOF >/usr/local/etc/php/conf.d/zz-xdebug.ini
xdebug.remote_host = ${XDEBUG_REMOTE_HOST:-localhost}
xdebug.remote_port = ${XDEBUG_REMOTE_PORT:-9000}
xdebug.remote_enable = ${XDEBUG_REMOTE_ENABLE:-0}
EOF

  exit
fi
